export const ARTICLE_LIST_LOADING = "ARTICLE_LIST_LOADING"
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS"
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL"

export const ARTICLE_LOADING = "ARTICLE_LOADING"
export const ARTICLE_SUCCESS = "ARTICLE_SUCCESS"
export const ARTICLE_FAIL = "ARTICLE_FAIL"